apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugbi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yugbi
  template:
    metadata:
      labels:
        app: yugbi
    spec:
      containers:
      - image: okteto.dev/yugbi:latest
        name: yugbi
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b664b0b9-0d35-4155-9918-7b6eb98180dc"
        - name: Vless_Path
          value: "/vl589hj5"
        - name: Vmess_UUID
          value: "b664b0b9-0d35-4155-9918-7b6eb98180dc"
        - name: Vmess_Path
          value: "/vm6hvg6"
        - name: Share_Path
          value: "/v2link"
